name: Build job
on:
  workflow_dispatch:
    inputs: {}

env:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: ${{ matrix.OS_NAME }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Debug, Release]
        include:
        - os: ubuntu-latest
          OS_NAME: Linux x64
          RELEASE_ZIP_OS_NAME: linux_x64

        - os: windows-latest
          OS_NAME: Windows x64
          RELEASE_ZIP_OS_NAME: win_x64

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x
        
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Get git short hash
        id: git_short_hash
        run: echo "result=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Build
        run: dotnet build -c "${{ matrix.configuration }}" -p:SourceRevisionId="${{ steps.git_short_hash.outputs.result }}" -p:ExtraDefineConstants=DISABLE_UPDATER

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LethalVibrations-${{ matrix.configuration }}+${{ steps.git_short_hash.outputs.result }}-${{ matrix.RELEASE_ZIP_OS_NAME }}
          path: LethalVibrations/bin
